# Assignment 3 - Questions and Answers

# Task 1 - Question

List all the selection mechanisms, both parent and survivor, that you
have learned about and discuss their properties.

Note: not all of the selection idea listed below were discussed in
detail or included on the PowerPoint slides, so we do not expect anyone
to list all of these. Some of the more important forms of selection are
bolded below.

# Task 1 - Answer

Types of selection mentioned include:

### A)  Mating Selection (choosing who will become "parents"):

<!-- -->

1)  **Fitness-proportional selection (or "proportional selection"), in
    which individuals are chosen for mutation or crossover or continuing
    unmodified into the next generation based on their relative
    fitnesses (relative to others in the current population)**

    a.  Original GAs used this form

    b.  Disadvantage: as population fitnesses rise, relative fitnesses
        approach 1, and little distinction is made between best and
        worst individuals. Therefore, it is rarely used today

    c.  Two major forms are used for fitness-proportional selection:

        i.  Roulette Wheel Selection, in which a portion of the
            probability space [0., 1.] is allocated to each
            individual, proportional to its relative fitness, and
            uniformly chosen random numbers determine each choice of an
            individual to become a parent

        ii. Stochastic Universal Sampling, which uses the relative
            fitness distribution as above, but choice of a single random
            number (a "bias") determines the initial individual chosen,
            then 1/popsize selectors, evenly spaced, are added to that
            bias to determine all of the remaining parents---whatever
            "pie slice" a selector hits is sampled. This produces a
            fitness-proportional distribution with lower variance than
            Roulette Wheel Selection.

2)  Scaled fitness-proportional selection, in which the ratio of scaled
    fitness values of the best-fitness and mean-fitness individuals is
    kept constant (or some similar scheme)

    d.  Can help to avoid the problem in 1) b. above, but then the
        fitness of a chromosome varies with each generation, which may
        sometimes be a disadvantage

3)  Rank-based selection, in which individuals are sorted by fitness
    values, then each rank has its own specified chance of being chosen

    e.  Requires sorting of population at each generation, which could
        be costly for large population sizes

    f.  Still leaves question of what fraction should be allocated to
        each rank for the user to decide

4)  **Tournament selection, in which, for each parent to be chosen,
    *tourneysize* individuals are picked at uniform random, and the
    highest-fitness individual of those *tourneysize* individuals is
    chosen to be a parent**

    g.  Requires only one additional parameter, the tourneysize

    h.  Selection pressure can be controlled in a relatively constant
        manner by a single choice of tourneysize

    i.  Not subject to requirements to sort or rescale, nor does ability
        to distinguish among fitnesses shrink as evolution progresses

    j.  Very commonly used in practice

5)  Variations on tournament selection in which each individual is
    guaranteed a spot in one tournament, producing similar results but
    with lower variance in probability of selection

    k.  As above, but allows reduction in the variance among parents
        selected

6)  Variations on tournament selection, such as picking the top two of
    *tourneysize* individual as the ones to be crossed over

    l.  Can reduce computational overhead, but usually only to a trivial
        extent

    m.  Slightly weakens selection pressure compared with 4) or 5) above

7)  **Uniform probability of being selected for survival, mutation,
    crossover... i.e., all selection pressure is applied at the survival
    stage, not in selecting individuals to be mutated, crossed over, or
    continuing unmodified**

    n.  Nature of selection and selection pressure then depend only on
        the selection at the survival stage

8)  Mating restrictions exert a form of selection pressure, in a less
    direct way

    o.  May be useful if the nature of the problem makes certain types
        of matings undesirable, infeasible, etc.

    p.  By prohibiting certain matings, affects the probability
        distribution of matings among the potential parents, so affects
        selection pressure, but in a way that is difficult to quantify

<!-- -->

### B)  Survival/Replacement Selection (of individuals to survive into next
    generation after mutation/crossover performed)

<!-- -->

1)  **Offspring replace their parents deterministically**

    a.  Original replacement strategy used in simple GAs

    b.  Can help to slow convergence, but also allows possible loss of
        the best individual found to date, unless combined with some
        form of elitism

2)  **Offspring replace their parents if their fitness is better (than
    one or than both)**

    c.  Stronger selection pressure than 1), which might cause more
        rapid convergence than desired (or might not, of course)...

    d.  Less selection pressure than Mu + Lambda (below), as the
        selection is more "local"

3)  **Offspring generated replace any parents (not necessarily their
    own), usually those parents with below-average or the worst
    fitnesses**

    e.  Replacing worst in population is frequently used, and doesn't
        seem to introduce high selection pressure

4)  **Offspring generated are pooled with all parents and popsize of
    them survive (similar to (Mu + Lambda) below, but with no
    specification of size of Mu relative to Lambda**

    f.  Preserves elite parents and children

    g.  Similar to 6) below, and commonly used, but can cause fairly
        rapid convergence (depending on the problem)

5)  **(Mu, Lambda) selection, in which the Lambda parents generate
    Mu\>Lambda offspring, and the best Lambda of those offspring replace
    all Lambda parents**

    h.  Commonly used with Evolutionary Strategies operators, but
        increasingly, also with other evolutionary algorithms

    i.  Does not have elite preservation property of 2), 4) and 6)

    j.  Less selection pressure than 6; sometimes 5) works better;
        sometimes 6)

6)  **(Mu + Lambda) selection, in which the Lambda parents generate
    Mu\>Lambda offspring, and the best Lambda of the (Mu + Lambda)
    parents and offspring survive**

    k.  Commonly used with Evolutionary Strategies operators, but
        increasingly, also with other evolutionary algorithms

    l.  Does preserve elite solutions (i.e., best solution found is
        never lost)

    m.  Traded off with 5); each is sometimes better

# Task 2 - Question

Let S1={1\*\*\*10\*\*00\*\*} and S2={\*\*\*1\*01\*\*\*\*\*} be two
schemata.

1\. Give the order and the defining length of S1 and S2.

2\. What is the probability for one-point crossover with crossover rate
$p_c$ that crossover breaks S1, or S2? (i.e., the probability that the
child created by the operator does not belong to the given schema,
assuming each is crossed over with a mate that does not match it in any
of the positions with a value specified.)

3\. What is the probability that mutation with mutation rate $p_m$ breaks
S1, or S2?

4\. What is the probability that S1 or S2 survive the application of both
crossover and mutation?

5\. Is it correct to call one of these two schemata a "building block"?
Explain why, or why not.


# Task 2 - Answer

1.  Order (the number of positions specified, not \*'s) of S1, o(S1) =
    5; o(S2) = 3. Defining length ∆ (number of spots 1-point crossover
    could disrupt) of S1, ∆(S1) = 9; ∆(S2) = 3.

2.  Assuming that crossover is with an individual that does not match S1
    at any locus (extremely unlikely for binary chromosomes, but much
    more likely otherwise), the probability that 1-point crossover
    disrupts S1 is ∆(S1) / (len (S1)-1) = 9/11 ~= 0.8181.

    Similarly, the probability that 1-point crossover disrupts S2 is
    ∆(S2) / (len (S2)-1) = 3/11 = 0.2727.

3.  Probability that mutation (at rate $p_m$ per locus) does not change a
    particular locus is (1-$p_m$). Therefore mutation does NOT break S~1~
    with probability (1 - $p_m$) \*\* o(S1) = (1 - $p_m$)\*\*5; that is,
    in order NOT to disrupt the schema requires that all o(S1) loci NOT
    be disrupted, so is the product of their probabilities. Therefore,
    the probability that mutation DOES break S1 is 1 - (1 - $p_m$)\*\*5.
    Similarly, mutation breaks S2 with probability 1 - (1 - $p_m$)\*\*o(S2) =

    1 - (1 - $p_m$)\*\*3. That is, NOT to disrupt S requires NOT
    disrupting at each of the o(S) positions, each of which occurs with
    probability (1 - $p_m$), and there are o(S) of those ALL of which must
    not be disrupted, so probabilities multiply. The chance of
    disrupting the schema is one minus the chance of NOT disrupting it.

4.  To survive both crossover and mutation, a schema must NOT be
    disrupted by mutation AND not disrupted by crossover, so we multiply
    those NOT disrupted probabilities to get the probability that
    neither disrupts the schema. Probability that schema S is not
    disrupted by *crossover* is (1 - ∆(S) / (len (S)-1)). Probability that
    schema S is not disrupted by *mutation* is (1 - pm)\*\*o(S) . So
    for schema S1, probability **not disrupted** by either crossover or
    mutation is:

    (1 - (∆(S1) / (len (S1) - 1)) \* (1 - $p_m$)\*\*o(S1) = (1 - .8181) \* (1 -
    $p_m$)\*\*5 ~= .1818 \* (1 - $p_m$)\*\*5

    And for schema S2:

    (1 - (∆(S2) / (len (S2) - 1))) \* (1 - $p_m$)\*\*o(S2) = (1 - .2727) \* (1 -
    $p_m$)\*\*3 ~= .7272 \* (1 - $p_m$)\*\*3

5.  A building block is defined as a schema that is:

    a\) short,

    b\) low-order, and

    c\) high-fitness

    S1 is NOT a building block. Relative to a total chromosome length
    of 12 bits, 9 (= defining length of S1) seems long, so S1 would not
    be considered a building block (it's also not very low-order, its
    order being 5).

    The defining length of S2, namely 3, is much shorter relative to 12,
    and its order is only 3, which is relatively low-order, so IF S2 is
    of relatively **high fitness**, it might well be considered a
    building block. If its fitness is not high, then it would NOT be
    considered a building block.


# Task 3 - Solution and Discussion 

The problem asks for a comparison of a GA versus enumeration for finding a solution to the Eight Queens problem.  There is something different about this problem, however, from the usual enumeration problem:  in the “usual” enumeration problem, one must calculate and evaluate all possible solutions (i.e., enumerate them all) in order to know which one is best.  But in the Eight Queens problem, there is a solution criterion known in advance (namely, 0 attacks) that allows the enumeration to be stopped as soon as any solution that satisfies it is found.  Similarly, we can (and I hope you did!) stop the GA whenever it finds a solution with no attacks.  It would be a hard task for a GA to find ALL solutions to this problem—we can stop it as soon as it finds one solution with no attacks.  Thus, to compare the two algorithms, what we should be comparing is the average number of evaluations it takes a GA to find ONE solution versus the average number of evaluations it takes enumeration to find ONE solution (its first legal solution).  The easiest way to do that enumeration task, in this small case with only 8 queens, is to run the enumeration once, tabulating the number of permutations and the number of them that are legal solutions.  Then one can calculate the average number of evaluations needed to find a solution via enumeration, assuming it were started from a random initial arrangement of queens (with only one per row and column).  

### Exhaustive Search

The ’C’ program appended does that, finding that there are 40,320 total permutations of the queens, and 92 of them are legal solutions to the eight queens problem.  That allows calculating the average time to find a solution by enumeration (if done from random starting points) as 443.26 evaluations.  That is about double the number of evaluations required by the GA (see Table I below), which is about 220, and, of course, that would become far more dramatic if the number of queens were larger.  I also implemented a version of the exhaustive search that starts from a random arrangement (one queen per row/column) and permutes them by Heap’s Algorithm until finding a first correct solution, then stops. The results of that algorithm are shown in the second column of Table I, and compared statistically with the GA results.

### Genetic Algorithm

I used the GALOPPS GA package (in ‘C’) that I wrote to do the GA solutions, using the same functions to calculate attacks as in the exhaustive code, and using order crossover and swap mutation as described in class. Unfortunately, I am not able to run it in the Jupyter Notebooks environment, so I am showing the results of 30 runs of the GA in Table I, showing in each case how many permutations it evaluated, starting from a random one, until finding a legal solution.  

### Discussion

There are many ways to attack the enumeration problem, including:

1) You might enumerate all possible combinations of 8 queens among 8 the columns, which is 8**8, or 16,777,216 arrangements.  But that ignores the fact that we are not allowing any row to contain more than one queen, so is not a good way to solve this problem.

2) You might recognize that you could enumerate column by column, so have 8 choices for the first column, then 7 for the second, then 6 for the third, etc., yielding 8! or 40,320 possibilities in total to be checked for any attacks. 

3) You might recognize that each of these 8! solutions that has only one queen in any row or column is a permutation of any other such solution, a permutation of the numbers (1,2,3,4,5,6,7,8). (There are lots of ways to see this… including just permuting the COLUMNS of any initial solution (1 queen in each row, each column) without moving the rows of the queens in those columns, and there are 8! ways to do this. Each such permutation, of course, results in having only one queen in each row and each column.)  Storing the row index of the queen in each column is the “representation” that we suggested you use in your genetic algorithm solution of the problem.  Permuting these solutions is a much more efficient way to enumerate all possible board arrangements with exactly one queen per row or column.  There are only 8! or 40,320 such arrangements, so a much smaller number of arrangements to enumerate than 8**8.  We’ll discuss this in 4) below.

4) To attack the enumeration problem DIRECTLY, we need our enumeration algorithm to be capable of producing all possible permutations, each exactly once, starting from an arbitrary permutation, and that is non-trivial to do.  B. R. Heap invented such an algorithm in 1963.  I have implemented his algorithm in a C program (my native language) and run 30 instances of it, each beginning with a different randomly chosen permutation.  Since you can’t run it in the Jupyter Notebook environment, I haven’t listed it here, but instead listed the code for the solution enumerating all solutions.  

5) Of course, you could use the method I did above under “Exhaustive Search” and enumerate ALL solutions and divide the size of the search space by the total number of solutions found.  Perhaps some of you have done that.  


But I also implemented the direct enumeration approach, stopping as soon as a legal solution is found. The difference in means between the GA and enumeration approaches appears obvious, but perhaps not as large as a naïve comparison of average GA run time with TOTAL time to enumerate ALL solutions might have led you to believe—there are many solutions (namely, 92) that satisfy the 0-attacks criterion, so the average or median time to find the first one of them is much less than the total time to enumerate all solutions.  Here, 40,320/92 = 438.26, which is near the mean of what our direct (stopping at first success) enumeration algorithm below produced.

If we wanted to use these runs to demonstrate that the mean solution times of the two algorithms are different statistically, we would perform a statistical test on data such as those in Table I.  Since we have no assurance that these evaluation numbers are normally distributed, rather than using something like a Student t-test, we use a Mann-Whitney U Test (also called the Wilcoxon Rank Sum Test or the Mann-Whitney-Wilcoxon Test), which sorts all 60 values, and then calculates the probability that the resulting order of outputs from the two algorithms would occur in that fashion due to chance.  If the samples were paired rather than independent, we would instead use the Wilcoxon Signed Rank Test, a very similar test also heavily used in analyzing data produced by evolutionary computation.  Doing this Mann-Whitney U Test on these data produces the result that the difference is statistically significant at the level of 0.01044.  That is, the chance that such a set of results would occur if the two underlying distributions were identical is less than 0.01044, well below the level of .05 often used for such testing, but not so ridiculously small as to be essentially impossible.   This is a typical test used to compare results generated by evolutionary computation algorithms, if there is no assurance that their distributions are Gaussian (normal).

Table I: Number of solution evaluations to find a legal solution by a GA vs. by enumeration on Eight Queens.  

| Run | Evals GA | Evals exhaustive |
| :- | -: | :-: |
| 1 | 149 | 460 |
| 2 | 227 | 77 | 
| 3 | 572 | 1130 | 
| 4 | 59 | 667 | 
| 5 | 373 | 28 | 
| 6 | 425 | 431 | 
| 7 | 346 | 842 | 
| 8 | 214 | 300 | 
| 9 | 291 | 56 | 
| 10 | 82 | 2053 | 
| 11 | 67 | 552 | 
| 12 | 112 | 133 | 
| 13 | 67 | 819 | 
| 14 | 38 | 898 | 
| 15 | 503 | 192 | 
| 16 | 156 | 29 | 
| 17 | 436 | 195 | 
| 18 | 142 | 409 | 
| 19 | 82 | 1505 | 
| 20 | 296 | 121 | 
| 21 | 231 | 249 | 
| 22 | 85 | 373 | 
| 23 | 465 | 865 | 
| 24 | 248 | 7 | 
| 25 | 179 | 245 | 
| 26 | 388 | 445 | 
| 27 | 449 | 1192 | 
| 28 | 86 | 1053 | 
| 29 | 97 | 218 | 
| 30 | 359 | 1100 | 
| Mean | 240.8 | 554.8 |
| Median | 220.5 | 420.0 |
| Std. Dev. | 157.0 | 499.2 |


    ## ‘C’ Code for Generating ALL Legal Solutions to the Eight Queens Problem via Enumeration (WILL NOT EXECUTE IN THIS CONTEXT... COPY AND USE gcc <filename> to compile, use a.out to execute.

In [ ]:
/* Routine to count the solutions to 8 queens problem by exhaustive search */
/* This version calculates ALL legal solutions by exhaustion. */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define NQUEENS 8

int  CheckAttacks(int *Queens);
void generate(int k, int *Queens);
void swap(int *first, int *second);

int  NPermsChecked = 0;
int  NSolutions = 0;

int
main(void)
{
   int Queens[NQUEENS] = {0,1,2,3,4,5,6,7};
   time_t t;
   int seed;

   seed = time(NULL);
   srand(seed);
   /* Just use 0-7 in order as starting arrangement; will enumerate all, */
   /* so it doesn't matter where start. */
   /* Generate all possible permutations of Queens, starting from this */
   /* starting arrangement, using Heap's Algorithm (see Wikipedia entry).   */
   /* At each step, the current permutation is stored in Queens. */
   /* Calculate all solutions, counting both number tried and number found. */
   generate(NQUEENS, Queens);
   fprintf(stdout, "\nPermutations %d, Solns Found %d\n", NPermsChecked, NSolutions);
}

void
generate(int k, int *Queens)
{
   /* Implementation of Heap's Algorithm to enumerate permutations */
   int i, row, Attacks;

   if (k == 1) {
      NPermsChecked++;
      /* Permutation complete; check this permutation for legal, record successes. */
      NSolutions += !CheckAttacks(Queens);
   }
   else {
      for (i=0;i<k;i++) {
          generate(k - 1, Queens);
          if (k % 2 == 0) swap(&(Queens[0]), &(Queens[k-1]));
          else swap(&(Queens[i]), &(Queens[k-1]));
      }
   }
   return;
}

int
CheckAttacks(int *Queens)
{
   /* Check queen in each row to see if it attacks a queen in later rows. */
   /* Can stop when find first attack, of course. */
   int row, row2, CkQueen;
   int Attacks = 0;

   for (row=0;row<NQUEENS;row++) {
      CkQueen = Queens[row]; /* column of queen in row row. */
      for (row2=row;row2<NQUEENS;row2++) {
         if (row != row2 && abs(row-row2) == abs(CkQueen-Queens[row2])) {
            /* equal absolute values means on same diagonal */
            Attacks = 1;
            return (Attacks);
         }
      }
   }
   return (Attacks);
}

void
swap(int *first, int *second)
{
   int temp;

   temp = *first;
   *first = *second;
   *second = temp;
   return;
}

### Example Student Solution to Task 3  (thanks to Robert Shrote)

In [ ]:
import numpy

#### Step 1: Make a scoring function

In [ ]:
def objfn(geno):
    """
    8 queens objective function.
    max = 28
    min = 0
    Goal is to minimize.
    
    Parameters
    ----------
    geno : numpy.ndarray
        1d array representing the genotype of an individual.
    
    Returns
    -------
    violations : int
        Number of violations for queens
    """
    violations = 0
    for i in range(len(geno)):
        for j in range(i+1, len(geno)):
            # calculate slope
            slope = (geno[j]-geno[i]) / (j-i)
            # check row and diagonal violations
            if (geno[i] == geno[j]) or (slope == 1) or (slope == -1):
                violations += 1
    return violations


Run some tests for `objfn`...

In [ ]:
t1 = numpy.array([1,2,3,4,5,6,7,8])
print(objfn(t1))
t2 = numpy.array([1,1,1,1,1,1,1,1])
print(objfn(t2))
t3 = numpy.array([8,7,6,5,4,3,2,1])
print(objfn(t3))

28
28
28


#### Step 2: Make an exhaustive search algorithm to search for the chess arrangement

In [ ]:
def permute(a, b):
    """
    A recursive generator function to yield permuations of an input.
    
    Parameters
    ----------
    a : numpy.ndarray
        Input array to be sampled from.
    b : numpy.ndarray
        Output array to be yielded if the lenght of a is 0.
    
    Yields
    ------
    b : numpy.ndarray
        The output array if len(a == 0)
    """
    if len(a) == 0:
        yield numpy.array(b)
    for i in range(len(a)):
        btmp = numpy.append(b, a[i])
        atmp = numpy.delete(a, i)
        yield from permute(atmp, btmp)

Run a test for `permute`...

In [ ]:
import math
a = numpy.int8([1,2,3,4])
b = numpy.int8([])

i = 0
for k in permute(a,b):
    i+=1

print(i)
print(math.factorial(len(a)))

24
24


In [ ]:
def exhaustive_search(geno, target = 0):
    """
    Perform exhaustive search for 8 queens problem.
    
    Parameters
    ----------
    geno : numpy.ndarray
        Starting board configuration to work with.
    target : int
        Target score
    
    Returns
    -------
    k : numpy.ndarray, None
        Found board configuration or None if no boards are found.
    ntests : int
        Number of function evaluations
    """
    out = numpy.array([], dtype=geno.dtype)
    ntests = 0
    for k in permute(geno, out):
        score = objfn(k)
        ntests += 1
        if score == target:
            return k, ntests
    return None, ntests

Test the exhaustive search algorithm...

In [ ]:
geno = numpy.arange(8)+1
numpy.random.shuffle(geno)
print("Start:", geno)
soln, ntests = exhaustive_search(geno)
print("Solution:", soln)
print("N tests:", ntests)

Start: [1 7 8 6 4 5 2 3]
Solution: [1 7 4 6 8 2 5 3]
N tests: 267


#### Step 3: Make an evolutionary algorithm

##### Create initialization function

In [ ]:
def initialize(n, p):
    """
    Initialize breeding population
    
    Parameters
    ----------
    n : int
        Number of breeding individuals
    p : int
        Number of rows/columns on the chess board.
    
    Returns
    -------
    pop : numpy.ndarray
        A 2D array of shape (n, p) containing breeding individuals
    """
    # copy 1-p, n times
    pop = numpy.tile(numpy.arange(p)+1, (n,1))
    
    # shuffle along the second axis
    for i in range(n):
        numpy.random.shuffle(pop[i])
        
    return pop

Run tests...

In [ ]:
a = initialize(10, 8)
print(a)

[[3 8 1 6 5 7 4 2]
 [8 6 3 2 7 1 5 4]
 [3 5 4 1 8 7 2 6]
 [5 2 1 3 7 6 8 4]
 [5 8 1 6 7 4 2 3]
 [3 8 7 2 1 6 4 5]
 [6 1 4 2 3 8 5 7]
 [6 2 8 7 3 5 1 4]
 [4 5 1 2 3 6 8 7]
 [8 4 1 5 2 6 7 3]]


##### Create population evaluation function

In [ ]:
def evaluate(pop, fn, sign = 1):
    """
    Evaluate a population using an objective function
    
    Parameters
    ----------
    pop : numpy.ndarray
        A 2D array containing breeding individual chromosomes
    fn : callable
        Objective function
    sign : int
        1 or -1 to alter objective function sign
        
    Returns
    -------
    score : numpy.ndarray
        A 1D array containing scores for the population.
    """
    score = numpy.array(
        [(sign * fn(pop[i])) for i in range(len(pop))]
    )
    return score

Run tests...

In [ ]:
pop = initialize(5, 8)
print(pop)

s = evaluate(pop, objfn, sign = 1)
print(s)

[[4 8 2 7 5 1 3 6]
 [8 3 5 4 7 6 1 2]
 [1 7 3 5 6 2 4 8]
 [2 5 1 3 8 6 7 4]
 [7 1 8 2 6 5 4 3]]
[ 5  7  6  4 11]


##### Create parental selection operator: uniform selection

In [ ]:
def uniform_parental_selection(pop, pscore, mu):
    """
    Perform uniform parental selection selection
    
    Parameters
    ----------
    pop : numpy.ndarray
        A 2D array containing breeding individual chromosomes
    pscore : numpy.ndarray
        A 1D array containing scores for the population.
    mu : int
        Number of parents to select
    
    Returns
    -------
    parents: numpy.ndarray
        A 2D array containing parental chromosomes.
    score : numpy.ndarray
        A 1D array containing scores for the selected parents.
    """
    parents = numpy.random.choice(
        numpy.arange(len(pop)),
        size=mu,
        replace=True
    )
    return pop[parents], pscore[parents]

Run tests...

In [ ]:
pop = initialize(5, 8)
print(pop)
pscore = evaluate(pop, objfn)
print(pscore)

p, s = uniform_parental_selection(pop, pscore, 10)
print(p)
print(s)

[[5 8 7 1 2 3 4 6]
 [8 2 6 4 1 3 5 7]
 [1 3 5 7 4 6 8 2]
 [7 2 5 8 1 6 3 4]
 [2 7 1 6 4 8 3 5]]
[8 4 2 8 3]
[[2 7 1 6 4 8 3 5]
 [8 2 6 4 1 3 5 7]
 [8 2 6 4 1 3 5 7]
 [1 3 5 7 4 6 8 2]
 [2 7 1 6 4 8 3 5]
 [2 7 1 6 4 8 3 5]
 [1 3 5 7 4 6 8 2]
 [1 3 5 7 4 6 8 2]
 [7 2 5 8 1 6 3 4]
 [2 7 1 6 4 8 3 5]]
[3 4 4 2 3 3 2 2 8 3]


##### Create recombination operator: Recombines using student's own, looks like single-point crossover with repair to work with permutation representation, with probability p.

In [ ]:
def recombine_1pt(male, female, p = 1.0):
    """
    Recombine (single-point) male and female individuals to produce 2 progeny per pair.
    
    Parameters
    ----------
    male : numpy.ndarray
        A 2D array containing male parental chromosomes.
    female : numpy.ndarray
        A 2D array containing female parental chromosomes.
    p : int
        Probaility of recombination for a given pair of individuals.
    
    Returns
    -------
    children : numpy.ndarray
        A 2D array containing progeny chromosomes.
    """
    children = []
    for a, b in zip(male,female):
        atmp, btmp = a, b

        # determine if we're going to crossover
        xo = numpy.random.choice([True,False], p=[p,1-p])
        if xo:
            # copy arrays
            atmp, btmp = numpy.copy(a), numpy.copy(b)

            # crossover occurs directly before this index [1,7]
            xopos = numpy.random.randint(1, len(a))

            # crossover a with b
            i = xopos
            for e in numpy.append(b[xopos:],b[:xopos]):
                if not (e in atmp[:xopos]):
                    atmp[i] = e
                    i += 1
            # crossover b with a
            i = xopos
            for e in numpy.append(a[xopos:],a[:xopos]):
                if not (e in btmp[:xopos]):
                    btmp[i] = e
                    i += 1
        
        children.append(numpy.copy(atmp))
        children.append(numpy.copy(btmp))
    
    return numpy.stack(children)

Run tests...

In [ ]:
a = numpy.arange(8)
b = numpy.arange(8)
a = numpy.tile(a, (5,1))
b = numpy.tile(b, (5,1))
for i,j in zip(a,b):
    numpy.random.shuffle(i)
    numpy.random.shuffle(j)
print(a)
print(b)

children = recombine_1pt(a, b)
print(children)

[[0 2 4 7 1 6 3 5]
 [7 5 2 1 0 4 3 6]
 [3 0 1 4 5 6 7 2]
 [6 3 7 1 0 5 2 4]
 [6 7 3 4 1 2 0 5]]
[[7 0 3 2 1 4 6 5]
 [3 0 6 1 4 2 7 5]
 [0 4 7 3 6 2 1 5]
 [6 3 4 5 7 1 2 0]
 [5 4 1 2 0 7 6 3]]
[[0 2 3 1 4 6 5 7]
 [7 0 4 1 6 3 5 2]
 [7 5 2 1 0 4 3 6]
 [3 0 6 1 4 2 7 5]
 [3 0 1 4 5 6 7 2]
 [0 4 7 3 6 2 1 5]
 [6 3 7 1 0 5 2 4]
 [6 3 4 5 7 1 2 0]
 [6 7 3 4 1 2 5 0]
 [5 4 1 2 0 7 6 3]]


##### Create the mutation operator: Randomly exchanges loci with probability p per locus.

In [ ]:
def mutate(pop, p):
    """
    Mutate loci by exchanging values at different loci along the same chromosome for an individual.
    
    Parameters
    ----------
    pop : numpy.ndarray
        A 2D array containing population chromosomes.
    p : int
        Probaility of mutation for a single locus.
    
    Returns
    -------
    children : numpy.ndarray
        A 2D array containing progeny chromosomes.
    """
    children = []
    for a in pop:
        # generate mask of loci to mutate
        mut = numpy.random.choice([True,False], size=a.shape, replace=True, p=[p,1-p])

        # loop through the mask to change values
        for i,m in enumerate(mut):
            if m == True:
                # generate index to exchange
                j = i
                while (j == i):
                    j = numpy.random.randint(0,len(a))
                # exchange indices
                a[i], a[j] = a[j], a[i]
        children.append(numpy.copy(a))
    
    return numpy.stack(children)


Run tests..

In [ ]:
a = numpy.arange(8)
a = numpy.tile(a, (5,1))
for i in a:
    numpy.random.shuffle(i)
print(a)


a = mutate(a, 0.1)
print(a)


[[0 5 4 1 3 7 6 2]
 [7 1 0 6 3 2 4 5]
 [3 6 7 1 2 5 4 0]
 [0 4 6 7 5 1 3 2]
 [7 1 3 5 4 6 2 0]]
[[0 7 4 5 3 1 6 2]
 [7 1 0 6 3 2 4 5]
 [3 0 4 5 2 1 7 6]
 [0 4 6 7 5 1 3 2]
 [7 3 0 5 4 2 6 1]]


##### Create child selection operator: mu + lambda selection

In [ ]:
def parent_child_selection(parents, pscore, children, cscore, mu):
    """
    Select top individuals from both parents and progeny by lowest score.

    Parameters
    ----------
    parents : numpy.ndarray
        A 2D array containing parental chromosomes.
    pscore : numpy.ndarray
        A 1D array containing scores for the parental population.
    children : numpy.ndarray
        A 2D array containing progeny chromosomes.
    cscore : numpy.ndarray
        A 1D array containing scores for the progeny population.
    mu : int
        Number of parents to select
    
    Returns
    -------
    children : numpy.ndarray
        A 2D array containing progeny chromosomes.
    """
    # merge arrays
    pop = numpy.concatenate([parents,children])
    score = numpy.concatenate([pscore,cscore])
    
    # get top (lowest) scoring indicies
    ix = score.argsort()[:mu]
    
    return numpy.copy(pop[ix]), numpy.copy(score[ix])


Run tests...

In [ ]:
parents = initialize(10, 8)
print("parents:","\n",parents)
children = initialize(10, 8)
print("children:","\n", children)

pscore = evaluate(parents, objfn, sign = 1)
cscore = evaluate(children, objfn, sign = 1)
print("pscore:","\n",pscore)
print("cscore:","\n",cscore)

nparent, nscore = parent_child_selection(parents, pscore, children, cscore, 10)
print("nparent:","\n",nparent)
print("nscore:","\n",nscore)

parents: 
 [[1 3 4 6 2 8 7 5]
 [4 7 1 8 5 6 2 3]
 [3 8 7 4 5 2 1 6]
 [5 1 8 4 3 7 2 6]
 [5 1 6 4 2 7 3 8]
 [7 6 5 3 2 4 8 1]
 [2 6 5 3 1 7 4 8]
 [4 7 3 2 8 1 5 6]
 [3 1 4 2 8 5 6 7]
 [7 6 2 3 5 8 1 4]]
children: 
 [[8 7 5 4 1 2 6 3]
 [1 4 7 2 8 6 5 3]
 [5 8 6 1 4 3 7 2]
 [6 2 3 4 5 8 7 1]
 [1 4 2 3 7 6 8 5]
 [3 6 1 7 2 8 5 4]
 [1 7 8 4 6 2 3 5]
 [1 7 4 8 6 5 2 3]
 [4 7 5 3 8 6 2 1]
 [6 1 8 2 5 4 3 7]]
pscore: 
 [6 4 7 2 1 4 2 5 7 4]
cscore: 
 [ 5  4  5 11  4  4  5  6  4  6]
nparent: 
 [[5 1 6 4 2 7 3 8]
 [5 1 8 4 3 7 2 6]
 [2 6 5 3 1 7 4 8]
 [7 6 2 3 5 8 1 4]
 [4 7 1 8 5 6 2 3]
 [7 6 5 3 2 4 8 1]
 [4 7 5 3 8 6 2 1]
 [1 4 7 2 8 6 5 3]
 [3 6 1 7 2 8 5 4]
 [1 4 2 3 7 6 8 5]]
nscore: 
 [1 2 2 4 4 4 4 4 4 4]


##### Put everything together into evolutionary algorithm

In [ ]:
def queens_evolutionary_algorithm(mu, lmbda, fn, pXO, pMut, target = 0, nqueens = 8):
    """
    Evolve a population to solve the 8-queens problem.
    
    Parameters
    ----------
    mu : int
        Number of parents
    lmbda : int
        Number of progeny (must be even)
    fn : callable
        Objective function to optimize
    pXO : float
        Probability of a 1pt crossover
    pMut : float
        Probability of a mutation (per locus)
    target : numeric
        Target objective function value (0 for function minimum)
    nqueens : int
        Number of queens/rows/columns on the board
        
    Returns
    -------
    config : numpy.ndarray
        Configuration of the solution board
    score : numeric
        Score associated with 'config'.
    neval : int
        Number of function evaluations to optimize.
    """
    # track number of evaluations
    neval = 0
    
    # initialize population
    pop = initialize(mu, nqueens)
    oscore = evaluate(pop, fn)
    
    # add number of evaluations
    neval += len(oscore)
    
    while oscore.min() != target:
        # choose parents for lmbda progeny
        parents, pscore = uniform_parental_selection(pop, oscore, lmbda)
        
        # recombine and mutate to make children
        children = recombine_1pt(parents[0::2], parents[1::2], pXO)
        children = mutate(children, pMut)
        
        # evaluate new progeny
        cscore = evaluate(children, fn)
        
        # add number of evaluations
        neval += len(cscore)
        
        # select top individuals from the parents + children
        pop, oscore = parent_child_selection(parents, pscore, children, cscore, mu)
    
    # get index of best scorer
    tix = numpy.argwhere(oscore == target)[0][0]
    
    return pop[tix], oscore[tix], neval


In [ ]:
p, o, n = queens_evolutionary_algorithm(40, 120, objfn, 1, 0.05, nqueens=8)
print(p)
print(o)
print(n)


[1 5 8 6 3 7 2 4]
0
280


#### Step 4: Run statistical tests on performance

In [ ]:
from scipy import stats

In [ ]:
ntrials = 200
exhaustive = []
evolutionary = []
for i in range(ntrials):
    geno = numpy.arange(8)+1
    numpy.random.shuffle(geno)
    soln, ntests = exhaustive_search(geno)
    exhaustive.append(ntests)

    p, o, n = queens_evolutionary_algorithm(40, 120, objfn, 1, 0.05)
    evolutionary.append(n)
    
    if i % 20 == 0:
        print(i)

exhaustive = numpy.array(exhaustive)
evolutionary = numpy.array(evolutionary)

0
20
40
60
80
100
120
140
160
180


In [ ]:
print("Exhaustive algorithm mean:", exhaustive.mean())
print("Evolutionary algorithm mean:", evolutionary.mean())

Exhaustive algorithm mean: 628.05
Evolutionary algorithm mean: 444.4


In [ ]:
# perform two sample t-test
statistic, pvalue = stats.ttest_ind(exhaustive, evolutionary)
print("Statistic", statistic)
print("p-value", pvalue)

Statistic 3.2274524902313453
p-value 0.0013524079075801201


#### Conclustions
The evolutionary algorithm requires less function evaluations $(p < 0.05)$ than the exhaustive algorithm to find a board with no conflicting queens.  [Instructor Note:  The mean for the exhaustive algorithm exceeds the expected mean.  The EA mean is higher than using the GA operators Goodman used, but may be correct for the operators used by this student.]